### ISSUE TITLE
Fake commit message isn't actually at the leap second boundary

### ISSUE THREAD

**Issue by dbussink** [vektra/tai64n#1]
Looks like the attempt was to create a commit at the leap second: https://twitter.com/evanphx/status/616019696572235776

But it was actually created at 12:00 UTC instead of 00:00:

```
commit 25016d31f91811a29f88fddfac0b482c3c6d2eee
Author: Evan Phoenix <evan@phx.io>
Date:   Wed Jul 1 12:00:00 2015 +0000

    The future is now
```

```
git log -1  --pretty=format:%at
1435752000
```

Can I blame improper usage of 24h clocks here? :wink:.

**Comment by evanphx** [comment]
I blame git! I tried really hard to do it but unix epoch clocks just repeated the last second!

**Comment by evanphx** [comment]
oh oh oh I see. OOPS! Yeah, 24h clocks. BAH

**Comment by dbussink** [comment]
> I blame git! I tried really hard to do it but unix epoch clocks just repeated the last second!

Yeah, that's how it's designed to work. Not doing that would break probably half the internet that assumes each day has 86400 seconds :smile:.
